# Generated by Django 5.0.4 on 2024-04-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.meetup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.participant')),
            ],
        ),
    ]
